version: "3"
services:
  # client:
  #   environment:
  #     - NODE_ENV="dev"
  #   build: ./client
  #   tty: true
  #   ports:
  #     - "3000:3000"
  #   container_name: youtube-url-container
  #   volumes:
  #     - ./client:/app
  #   command: sh -c "npm run dev"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    tty: true
    ports:
      - "5432:5432"
    restart: always
    user: root
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro

  app:
    container_name: app
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://app_user:password@postgres:5432/app_db?sslmode=disable
    links:
      - postgres:postgres
    restart: always
    depends_on:
      - postgres
